### ISSUE TITLE
Nosiphus Furniture Mod

### ISSUE THREAD

**Issue by strawberrynox** [MAXimized490/MandA-BofM#64]
CurseForge: https://www.curseforge.com/minecraft/mc-mods/nosiphus-furniture-mod
Version: 2023.12.9 https://www.curseforge.com/minecraft/mc-mods/nosiphus-furniture-mod/files/4944891
Environment: Server & Client
Type:  Mod
Dependency: Mr. Crayfish's Furniture Mod
Optional: No

**Comment by MAXimized490** [comment]
Please do not remove leading zeros from version numbers. Version numbers should match exactly with what the mod author puts on the file.
