### ISSUE TITLE
Paladin's Furniture

### ISSUE THREAD

**Issue by strawberrynox** [MAXimized490/MandA-BofM#65]
CurseForge: https://www.curseforge.com/minecraft/mc-mods/paladins-furniture
Version: 1.2 https://www.curseforge.com/minecraft/mc-mods/paladins-furniture/files/4861503
Environment: Server & Client
Type:  Mod
Dependency:  N/A
Optional: No

**Comment by MAXimized490** [comment]
Again, please write version numbers exactly as the mod author does. Do not remove seeming unnecessary parts, such as an ending ".0"
