### ISSUE TITLE
Add Pam's HarvestCraft 2 - Food Core

### ISSUE THREAD

**Issue by SirBaconDevs** [MAXimized490/MandA-BofM#75]
CurseForge: https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-core/files/5020789
Version: 1.0.3
Environment: CLIENT AND SERVER
Type: Items (Food)
Dependency: None
Optional: Nope
Note: It says its for 1.20.2 but supported versions are 1.20, 1.20.1 and 1.20.2

**Comment by MAXimized490** [comment]
The **Type** filed in the template is for the mod type (mod, utility, or dependency). Please make sure you review https://github.com/MAXimized490/MandA-BofM/wiki/Mod-Requests as instructed when filling out a request.
