### ISSUE TITLE
Add Pam's HarvestCraft 2 - Food Extended

### ISSUE THREAD

**Issue by SirBaconDevs** [MAXimized490/MandA-BofM#76]
CurseForge: https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-extended/files/4606448
Version: 1.0.0
Environment: CLIENT AND SERVER
Type: Items (Food)
Dependency: Pam's HarvestCraft 2 - Food Core
Optional: Nope

**Comment by MAXimized490** [comment]
The **Type** filed in the template is for the mod type (mod, utility, or dependency). Please make sure you review https://github.com/MAXimized490/MandA-BofM/wiki/Mod-Requests as instructed when filling out a request.
