### ISSUE TITLE
Add Pam's HarvestCraft 2 - Trees

### ISSUE THREAD

**Issue by SirBaconDevs** [MAXimized490/MandA-BofM#77]
CurseForge: https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-trees/files/4625518
Version: 1.0.2
Environment: CLIENT AND SERVER
Type: Generation (Not biomes tho just trees)
Dependency: Pam's HarvestCraft 2 - Food Core
Optional: Nope

**Comment by MAXimized490** [comment]
The **Type** filed in the template is for the mod type (mod, utility, or dependency). Please make sure you review https://github.com/MAXimized490/MandA-BofM/wiki/Mod-Requests as instructed when filling out a request.

**Comment by MAXimized490** [comment]
Pam's HarvestCraft 2 - Food Core is not a required dependency for this mod. Please make sure you only add required dependencies on mod requests.
https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-trees/relations/dependencies?page=1&type=RequiredDependency
